config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resource :search, only: [:create, :show]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :dashboards, only: [:index]
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  #has_and_belongs_to_many :railway_stations
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    if railway_stations.size > 0 && self.name.blank?
      self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
    end
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 stations")
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route], notice: 'Route created'
    else
      render :new
    end
  end

  def edit; end

  def update

    if @route.update(route_params)
      redirect_back(fallback_location: admin_routes_path, notice: 'Routes was successfully updated.')
    else
      render :edit
    end
  end

  def destroy

    @route.destroy
    redirect_to admin_routes_url
  end

  private

  def set_train
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for([:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}"} ) do |f| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
      <%= f.label :railway_station_ids, "Станции в маршруте" %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
</div>

  <div class="field">
    <%= f.label :train, "Train" %>
    <%= f.collection_select :trains, Train.all, :id, :number %>
  </div>

  <div class="actions">
     <%= f.submit t('.submit', action: route.new_record? ? t('common.create') : t('common.edit')), class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td>
    <div id="route_name_#{ route.id }">
      <%= route.name %>
    </div>
    <%= render 'form', route: route, hidden: true %>
  </td>
  <td><%= link_to t('common.show'), [:admin, route], class: "text-info" %></td>
  <td><%= link_to t('common.edit'), edit_admin_route_path(route), class: ["text-success", "edit_route"], data: { route_id: route.id } %></td>
  <td><%= link_to t('common.destroy'), [:admin, route], method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" %></td>
</tr>

app/views/admin/routes/edit.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Editing Route</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8 col-md-offset-1">
          <%= render 'form', route: @route, hidden: false %>
        </div>
        </div>
    </div>
    <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.show'), [:admin, @route], class: "text-info" %></li>
        <li>
          <%= link_to t('common.back'), admin_routes_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/admin/routes/index.html.erb
<h1>Routes</h1>


<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to t('common.show'), [:admin, route] %></td>
        <td><%= link_to t('common.edit'), edit_admin_route_path(route) %></td>
        <td><%= link_to t('common.destroy'), [:admin, route], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('admin.routes.new.title'), new_admin_route_path %>

app/views/admin/routes/new.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New Carriage</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
      <%= render 'form', carriage: @carriage %>
  </div>
  <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.back'), [:admin, @train] %>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>


<% if @route.trains.empty? %>
  <p>Поездов на маршруте нет</p>
<% else %>
  <p> Поезда на маршруте:</p>
    <table>
      <thead>
      </thead>
    </table>

      <ul>
      <% @route.trains.each do |train| %>
          <li><%= train.number %></li>
      <% end %>
      </ul>
<% end %>

<p>
  <strong>Stations:</strong>
  <% if @route.railway_stations.empty? %>
    Empty
  <% else %>
    <table>
      <thead>
      <tr>
       <td width="100px">Name</td>
       <td>Position</td>
       <th>Arrival - Departure</th>
      </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.ordered.each do |station| %>
        <tr>
          <td><%= station.title%></td>
          <td>
            <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
              <%= number_field_tag :position, station.position_in(@route)%>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag "Изменить" %>
            <% end %>
          </td>
          <td>
            <%= form_tag update_time_admin_railway_station_path(station), method: :patch do %>
              <%= time_field_tag :arrival, station.time(@route, :arrival) %>
              <%= time_field_tag :departure, station.time(@route, :departure) %>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag 'edit' %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    <table>

<% end %>
</p>



<% if @route.railway_stations.empty? %>
  <p>Поезд следует без остановок</p>
<% else %>
  <p> В маршруте есть следующие станции:</p>
    <table>
      <thead>
      </thead>
    </table>

      <ul>
      <% @route.railway_stations.each do |route| %>
          <li><%= route.title %></li>
      <% end %>
      </ul>
<% end %>

<%= link_to t('common.edit'), edit_admin_route_path(@route) %> |
<%= link_to t('common.back'), admin_routes_path %>