config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resource :search, only: [:create, :show]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :dashboards, only: [:index]
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  validates :number, uniqueness: { scope: :train_id,
    message: 'Number is already in use for this train' }

  def self.inherited(base)
    super
    def base.model_name
      superclass.model_name
    end
  end

  before_validation :add_number

  scope :coupe,    -> { where(type: 'CoupeCarriage') }
  scope :economy,  -> { where(type: 'EconomyCarriage') }
  scope :sitting,  -> { where(type: 'SittingCarriage') }
  scope :lux, -> { where(type: 'LuxCarriage') }
  scope :ordered, ->(asc = true) { order(number: asc ? :asc : :desc) }

  private

  def add_number
    if train
      max_number = Carriage.where(train: train).maximum(:number)
      self.number ||= max_number.nil? ? 1 : max_number.to_i + 1
    end
  end
end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create]

  def index
    @carriages = Carriage.all
  end

  def show; end

  def new
    @carriage = Carriage.new
  end

  def edit; end

  def create
    @carriage = @train.carriages.new(carriage_params)

    if @carriage.save
      redirect_to [:admin, @train], notice: 'Carriage was successfully created.'
    else
      render :new
    end
  end

  def update
    if @carriage.update(carriage_params)
      redirect_to admin_carriage_url(@carriage), notice: 'Carriage was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy

    redirect_to admin_carriages_url, notice: 'Carriage was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def carriage_params
    params.require(:carriage).permit(:number,
                                     :type,
                                     :train_id,
                                     :top_seats,
                                     :bottom_seats,
                                     :side_top_seats,
                                     :side_bottom_seats,
                                     :sitting_seats)
  end
end

app/views/admin/carriages/_carriage.html.erb
<% carriages.each do |carriage| %>
  <tr>
    <td><%= "#{carriage.type} - #{carriage.number} - #{carriage.train}" %></td>
    <td><%= link_to carriage.train.number, [:admin, carriage.train] %></td>
    <td><%= link_to t('common.back'), admin_carriage_path(carriage) %></td>
    <td><%= link_to t('common.edit'), edit_admin_carriage_path(carriage) %></td>
    <td><%= link_to t('common.destroy'), admin_carriage_path(carriage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/admin/carriages/_coupecarriage.html.erb
<p>
  <strong>Количество верхних мест:</strong>
  <%= @carriage.top_seats %>
</p>
<p>
  <strong>Количество нижних мест:</strong>
  <%= @carriage.bottom_seats %>
</p>

app/views/admin/carriages/_economycarriage.html.erb
<p>
  <strong>Количество верхних мест:</strong>
  <%= @carriage.top_seats %>
</p>
<p>
  <strong>Количество нижних мест:</strong>
  <%= @carriage.bottom_seats %>
</p>
<p>
  <strong>Количество верхних боковых мест:</strong>
  <%= @carriage.side_top_seats %>
</p>
<p>
  <strong>Количество нижних боковых мест:</strong>
  <%= @carriage.side_bottom_seats %>
</p>

app/views/admin/carriages/_form.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-1">
<%= form_for [:admin, @train, @carriage] do |f| %>
    <%= render 'common/errors', resource: @carriage %>

    <div class="field">
      <%= f.label :type, t('.type') %>
      <%= f.select :type, ["EconomyCarriage","LuxCarriage", "CoupeCarriage", "SittingCarriage"] , {}, class: "form-control" %>
    </div>

    <div class="field form-group" id="field_top_seats">
      <%= f.label :top_seats, "Количество верхних мест" %>
      <%= f.text_field :top_seats, class: "form-control" %>
    </div>

    <div class="filed form-group" id="field_bottom_seats">
      <%= f.label :bottom_seats, "Количество нижних мест" %>
      <%= f.text_field :bottom_seats, class: "form-control" %>
    </div>

    <div class="filed form-group" id="field_side_top_seats">
      <%= f.label :side_top_seats, "Количество нижних боковых мест" %>
      <%= f.text_field :side_top_seats, class: "form-control" %>
    </div>

    <div class="filed form-group" id="field_side_bottom_seats">
      <%= f.label :side_bottom_seats, "Количество верхних боковых мест" %>
      <%= f.text_field :side_bottom_seats, class: "form-control" %>
    </div>

    <div class="field form-group hidden-field" id="field_sitting_seats">
      <%= f.label :sitting_seats, "Количество сидячих мест" %>
      <%= f.text_field :sitting_seats, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :train_id, t('.train') %>
      <%= f.collection_select :train_id, Train.all, :id, :number, {}, class: "form-control" %>
    </div>

  <div class="actions">
    <%= f.submit t('.submit', action: carriage.new_record? ? t('common.create') : t('common.edit')), class: "btn btn-success" %>
  </div>
<% end %>
</div>
</div>

app/views/admin/carriages/_luxcarriage.html.erb
<p>
  <strong>Количество нижних мест:</strong>
  <%= @carriage.bottom_seats %>
</p>

app/views/admin/carriages/_sittingcarriage.html.erb
<p>
  <strong>Количество сидячих мест:</strong>
  <%= @carriage.sitting_seats %>
</p>

app/views/admin/carriages/edit.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Editing Carriage</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
    <%= render 'form', carriage: @carriage %>
    </div>
    <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.show'), admin_carriage_path(@carriage), class: "text-info" %>
        </li>
        <li>
          <%= link_to t('common.back'), [:admin, @carriage.train] %>
        </li>
      </ul>
    </div>
  </div>
  </div>
</div>

app/views/admin/carriages/index.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Carriages
      <span class="pull-right"><small>
        <%= link_to t('admin.carriages.new.title'), new_admin_train_carriage_path, class: "btn btn-success" %>
      </small></span>
    </h1>
    </div>
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Type</th>
          <th>Upper seats</th>
          <th>Lower seats</th>
          <th>Side Upper seats</th>
          <th>Side Lower seats</th>
          <th>Sitting seats</th>
          <th>Num in train</th>
          <th>Train</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "carriage", collection: @carriages %>
      </tbody>
    </table>
</div>
</div>

app/views/admin/carriages/new.html.erb
<h1>Добавить вагон</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to t('common.back'), [:admin, @train] %>

app/views/admin/carriages/show.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
  <h1>Carriage</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
      <p>
        <strong>Type:</strong>
        <%= @carriage.type %>
      </p>

      <%= render "#{@carriage.type.underscore}", carriage: @carriage %>

      <p>
        <strong>Train:</strong>
        <%= @carriage.train.number %>
      </p>
    </div>
    <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.edit'), edit_admin_carriage_path(@carriage), class: "text-success" %>
        </li>
        <li>
          <%= link_to t('common.back'), [:admin, @carriage.train] %>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>