config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resource :search, only: [:create, :show]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :dashboards, only: [:index]
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search
  include ActiveModel::Model

  attr_accessor :start_station, :end_station
  attr_accessor :start_station_id, :end_station_id
  attr_accessor :result

  def self.do(params = {})
    search = Search.new(
      start_station_id: params[:start_station_id],
      end_station_id: params[:end_station_id],
    )
    search.start_station = RailwayStation.find(params[:start_station_id])
    search.end_station = RailwayStation.find(params[:end_station_id])
    search.result = search.trains_by_route_station(search.start_station) & search.trains_by_route_station(search.end_station)
    search
  end

  def trains_by_route_station(station)
    Train.includes(route: :railway_stations).where(railway_stations: {id: station.id})
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.new
  end

  def create
    @search = Search.do(search_params)
    render :show
  end

  private

  def search_params
    params.require(:search).permit(:start_station_id, :end_station_id)
  end
end

app/views/searches/_form.html.erb
<%= form_for @search, url: { action: 'show' } do |f| %>
<div class="col-md-4">
  <div class="field">
    <%= f.label :start_station_id, t('.start_station') %>
    <%= f.collection_select :start_station_id, RailwayStation.all, :id, :title, {}, class: "form-control" %>
  </div>
</div>
<div class="col-md-4">
  <div class="field">
    <%= f.label :end_station_id, t('.end_station') %>
    <%= f.collection_select :end_station_id, RailwayStation.all, :id, :title, {}, class: "form-control" %>
  </div>
</div>
<div class="col-md-4">
  <div class="actions actions-find">
    <%= f.submit t('.submit'), class: "btn btn-primary form-control find" %>
  </div>
</div>
<% end %>

app/views/searches/_result.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Train</th>
      <th>Route</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @search.result.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= train.route.name %></td>
        <td><%= @search.start_station.time(train.route, :departure) %></td>
        <td><%= @search.end_station.time(train.route, :arrival) %></td>
        <td>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to t('tickets.buy'), new_admin_ticket_path(ticket: { train_id: train.id, start_station_id: @search.start_station.id, end_station_id: @search.end_station.id }), class: "btn btn-warning" %>
          <% else %>
          <%= link_to t('tickets.buy'), new_ticket_path(ticket: { train_id: train.id, start_station_id: @search.start_station.id, end_station_id: @search.end_station.id }), class: "btn btn-warning" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/searches/show.html.erb
<h1>Search Tickets</h1>

<div class="row">
  <%= render 'form' %>
</div>

<div class="row">
  <div class="col-md-12">
  <% if @search.result.present? %>
    <h2>Search results:</h2>
    <%= render 'result' %>
  <% end %>
  </div>
</div>