config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resource :search, only: [:create, :show]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    resources :dashboards, only: [:index]
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  has_many :tickets
  has_many :carriages

  validates :number, presence: true

  def count_seats_by_type(type_carriage, type_seat)
    carriages.where(type: type_carriage).sum(type_seat)
  end

  def count_carriages_by_type(type_carriage)
    carriages.where(type: type_carriage).count
  end

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains
  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  def update
    if @train.update(train_params)
      redirect_back(fallback_location: admin_trains_path, notice: 'Train was successfully updated.')
    else
      render :edit
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
      redirect_to admin_trains_url, notice: 'Train was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id)
    end
end

app/views/admin/trains/_carriages.html.erb
<ul>
  <li>Number:
    <% carriages.ordered(@train.order_carriages).each do |carriage| %>
      <%= link_to carriage.number, admin_carriage_path(carriage) %>
    <% end %>
  </li>
</ul>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Type carriage</th>
      <th>Number cars</th>
      <th>Upper</th>
      <th>Lower</th>
      <th>Side upper</th>
      <th>Side lower</th>
      <th>Sitting</th>
    </tr>
  </thead>
  <tbody>
    <% carriages.map(&:type).uniq.each do |carriage_type| %>
      <tr>
        <td><%= carriage_type %></td>
        <td><%= @train.count_carriages_by_type(carriage_type) %></td>
        <td><%= @train.count_seats_by_type(carriage_type, :top_seats) %></td>
        <td><%= @train.count_seats_by_type(carriage_type, :bottom_seats) %></td>
        <td><%= @train.count_seats_by_type(carriage_type, :side_top_seats) %></td>
        <td><%= @train.count_seats_by_type(carriage_type, :side_bottom_seats) %></td>
        <td><%= @train.count_seats_by_type(carriage_type, :sitting_seats) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/trains/_form.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-1">
<%= form_for([:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}"} ) do |f| %>
  <%= render 'common/errors', resource: train %>

  <div class="field form-group">
    <%= f.label :number %>
    <%= f.text_field :number, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :current_station_id, t('.current_station') %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title, {}, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :route_id, t('.route') %>
    <%= f.collection_select :route_id, Route.all, :id, :name, {},  class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: train.new_record? ? t('common.create') : t('common.edit')), class: "btn btn-success" %>
  </div>
<% end %>
</div>
</div>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_number_<%= train.id %>">
      <%= train.number %>
    </div>
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to t('common.show'), [:admin, train], class: "text-info" %></td>
  <td><%= link_to t('common.edit'), '', class: ["text-success", "edit_train"], data: { train_id: train.id } %></td>
  <td><%= link_to t('common.destroy'), [:admin, train], method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" %></td>
</tr>

app/views/admin/trains/edit.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Editing Train</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8 col-md-offset-1">
          <%= render 'form', train: @train, hidden: false %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.show'), [:admin, @train], class: "text-info" %>
        </li>
        <li>
          <%= link_to t('common.back'), admin_trains_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/admin/trains/index.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Trains
      <span class="pull-right"><small>
      <%= link_to t('admin.trains.new.title'), new_admin_train_path, class: "btn btn-success" %>
      </small></span>
    </h1>
  </div>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Number</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @trains %>
    </tbody>
  </table>
</div>
</div>

app/views/admin/trains/new.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New Train</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8 col-md-offset-1">
        <%= render 'form', train: @train, hidden: false %>
        </div>
      </div>
  </div>
  <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.back'), admin_trains_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/admin/trains/show.html.erb
<div class="row">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Train</h1>
  </div>
  <div class="panel-body">
    <div class="col-md-10">
  <p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Current Station:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Station is not assigned
  <% end %>
</p>

<p>
  <strong>Route:</strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Route is not assigned
  <% end %>
</p>

<p>
  <strong>Carriages:</strong>
    <% if @train.carriages.empty? %>
      train has no carriages
    <% else %>
      <%= render 'carriages', carriages: @train.carriages %>
    <% end %>
    <br>
  <%= link_to t('admin.carriages.new.title'), new_admin_train_carriage_path(@train), class: "btn btn-success" %>
</p>
    </div>
    <div class="col-md-2">
      <div class="col-md-2">
      <ul class="list-unstyled">
        <li>
          <%= link_to t('common.edit'), edit_admin_train_path(@train), class: "text-success" %>
        </li>
        <li>
          <%= link_to t('common.back'), admin_trains_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>